// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Asset is a finished recording the page can read.
 */
export class Asset {
    "assetId": string;

    /**
     * SizeBytes is the whole file; the page reads it in MaxReadBytes chunks.
     */
    "sizeBytes": number;

    /**
     * StartedDelayMs is how long after the request the first decodable frame
     * arrived, so the page can align this track with the others it recorded.
     */
    "startedDelayMs": number;
    "durationMs": number;

    /** Creates a new Asset instance. */
    constructor($$source: Partial<Asset> = {}) {
        if (!("assetId" in $$source)) {
            this["assetId"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("startedDelayMs" in $$source)) {
            this["startedDelayMs"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Asset instance from a string or object.
     */
    static createFrom($$source: any = {}): Asset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Asset($$parsedSource as Partial<Asset>);
    }
}

/**
 * Started is the handle for a recording in progress.
 */
export class Started {
    "recordingId": string;

    /** Creates a new Started instance. */
    constructor($$source: Partial<Started> = {}) {
        if (!("recordingId" in $$source)) {
            this["recordingId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Started instance from a string or object.
     */
    static createFrom($$source: any = {}): Started {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Started($$parsedSource as Partial<Started>);
    }
}
