// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Binding is what the page asks to watch.
 */
export class Binding {
    "kind": BindingKind;

    /**
     * Code is a physical DOM code such as "KeyV", for KindKeyboard.
     */
    "code"?: string;

    /**
     * Button is 0-4, for KindMouse.
     */
    "button"?: number;

    /** Creates a new Binding instance. */
    constructor($$source: Partial<Binding> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = BindingKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Binding instance from a string or object.
     */
    static createFrom($$source: any = {}): Binding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Binding($$parsedSource as Partial<Binding>);
    }
}

/**
 * BindingKind distinguishes the two things that can be bound.
 */
export enum BindingKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindKeyboard = "keyboard",
    KindMouse = "mouse",
};

/**
 * Capabilities reports whether this platform has background push-to-talk.
 */
export class Capabilities {
    "available": boolean;
    "detail": string;

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

/**
 * Snapshot is the state the page renders from.
 */
export class Snapshot {
    "sessionId": string;
    "sequence": number;
    "pressed": boolean;
    "healthy": boolean;
    "focused": boolean;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("pressed" in $$source)) {
            this["pressed"] = false;
        }
        if (!("healthy" in $$source)) {
            this["healthy"] = false;
        }
        if (!("focused" in $$source)) {
            this["focused"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}
