// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InstallInfo describes whether the runtime is present and what installing it
 * would cost.
 */
export class InstallInfo {
    "supported": boolean;
    "installed": boolean;
    "downloadBytes": number;
    "installedBytes": number;
    "detail": string;

    /** Creates a new InstallInfo instance. */
    constructor($$source: Partial<InstallInfo> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("downloadBytes" in $$source)) {
            this["downloadBytes"] = 0;
        }
        if (!("installedBytes" in $$source)) {
            this["installedBytes"] = 0;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallInfo($$parsedSource as Partial<InstallInfo>);
    }
}

/**
 * InstallResult is the outcome of an install attempt.
 */
export class InstallResult {
    "installed": boolean;
    "restartRequired": boolean;

    /** Creates a new InstallResult instance. */
    constructor($$source: Partial<InstallResult> = {}) {
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("restartRequired" in $$source)) {
            this["restartRequired"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallResult($$parsedSource as Partial<InstallResult>);
    }
}
