// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Status is what the settings screen renders.
 */
export class Status {
    "available": boolean;
    "installed": boolean;
    "detail": string;

    /**
     * Adapter names the GPU the graph was placed on, so someone can tell which
     * device is doing the work.
     */
    "adapter"?: string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
