// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CopilotFrame describes one signal the page is drawing.
 */
export class CopilotFrame {
    /**
     * MarkID identifies the signal across refreshes. It is the page's own mark
     * id, so a moving signal reuses its window instead of flickering.
     */
    "markId": string;

    /**
     * SessionID names the capture the signal belongs to. A signal for a
     * session that ended is refused rather than placed on the desktop.
     */
    "sessionId": string;

    /**
     * Corner is CopilotPoint or one of the four source corners.
     */
    "corner": string;
    "width": number;
    "height": number;

    /**
     * X and Y are the normalised position inside the source, used by
     * CopilotPoint.
     */
    "x": number;
    "y": number;

    /** Creates a new CopilotFrame instance. */
    constructor($$source: Partial<CopilotFrame> = {}) {
        if (!("markId" in $$source)) {
            this["markId"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("corner" in $$source)) {
            this["corner"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CopilotFrame instance from a string or object.
     */
    static createFrom($$source: any = {}): CopilotFrame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CopilotFrame($$parsedSource as Partial<CopilotFrame>);
    }
}

/**
 * Info is what the page needs to send frames the overlay will accept.
 */
export class Info {
    "overlayId": string;
    "width": number;
    "height": number;
    "maxWidth": number;
    "maxHeight": number;

    /**
     * MaxFrameBytes and MaxFPS let the page size and pace its own sends rather
     * than discovering the limits by being refused.
     */
    "maxFrameBytes": number;
    "maxFps": number;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("overlayId" in $$source)) {
            this["overlayId"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("maxWidth" in $$source)) {
            this["maxWidth"] = 0;
        }
        if (!("maxHeight" in $$source)) {
            this["maxHeight"] = 0;
        }
        if (!("maxFrameBytes" in $$source)) {
            this["maxFrameBytes"] = 0;
        }
        if (!("maxFps" in $$source)) {
            this["maxFps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}

/**
 * Options describe an overlay to open.
 */
export class Options {
    "position": Position;
    "size": Size;

    /**
     * ClickThrough lets the pointer reach whatever is underneath. A camera tile
     * over a game must not eat clicks.
     */
    "clickThrough": boolean;

    /**
     * Rows stacks that many 16:9 tiles vertically.
     */
    "rows": number;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("position" in $$source)) {
            this["position"] = Position.$zero;
        }
        if (!("size" in $$source)) {
            this["size"] = Size.$zero;
        }
        if (!("clickThrough" in $$source)) {
            this["clickThrough"] = false;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Options($$parsedSource as Partial<Options>);
    }
}

/**
 * Position is which corner of the display the overlay sits in.
 */
export enum Position {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TopLeft = "top-left",
    TopRight = "top-right",
    BottomLeft = "bottom-left",
    BottomRight = "bottom-right",
};

/**
 * Size is the overlay's width preset.
 */
export enum Size {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Small = "small",
    Medium = "medium",
    Large = "large",
};

/**
 * Update changes an open overlay. A nil field is left as it is.
 */
export class Update {
    "position"?: Position | null;
    "size"?: Size | null;
    "clickThrough"?: boolean | null;
    "rows"?: number | null;

    /** Creates a new Update instance. */
    constructor($$source: Partial<Update> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Update instance from a string or object.
     */
    static createFrom($$source: any = {}): Update {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Update($$parsedSource as Partial<Update>);
    }
}
