// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CopilotFrame describes one signal the page is drawing.
 */
export class CopilotFrame {
    /**
     * MarkID identifies the signal across refreshes. It is the page's own mark
     * id, so a moving signal reuses its window instead of flickering.
     */
    "markId": string;

    /**
     * SessionID names the capture the signal belongs to. A signal for a
     * session that ended is refused rather than placed on the desktop.
     */
    "sessionId": string;

    /**
     * Corner is CopilotPoint or one of the four source corners.
     */
    "corner": string;
    "width": number;
    "height": number;

    /**
     * X and Y are the normalised position inside the source, used by
     * CopilotPoint.
     */
    "x": number;
    "y": number;

    /** Creates a new CopilotFrame instance. */
    constructor($$source: Partial<CopilotFrame> = {}) {
        if (!("markId" in $$source)) {
            this["markId"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("corner" in $$source)) {
            this["corner"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CopilotFrame instance from a string or object.
     */
    static createFrom($$source: any = {}): CopilotFrame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CopilotFrame($$parsedSource as Partial<CopilotFrame>);
    }
}

export class CopilotPosition {
    "markId": string;
    "corner": string;
    "x": number;
    "y": number;
    "remainingMs": number;
    "revision": number;
    "trail"?: CopilotTrailPoint[];

    /** Creates a new CopilotPosition instance. */
    constructor($$source: Partial<CopilotPosition> = {}) {
        if (!("markId" in $$source)) {
            this["markId"] = "";
        }
        if (!("corner" in $$source)) {
            this["corner"] = "";
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("remainingMs" in $$source)) {
            this["remainingMs"] = 0;
        }
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CopilotPosition instance from a string or object.
     */
    static createFrom($$source: any = {}): CopilotPosition {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("trail" in $$parsedSource) {
            $$parsedSource["trail"] = $$createField6_0($$parsedSource["trail"]);
        }
        return new CopilotPosition($$parsedSource as Partial<CopilotPosition>);
    }
}

/**
 * Status describes actual source presentation, independently of delivery over
 * the call channel. Missing identifies artwork expired by the native lease.
 */
export class CopilotStatus {
    "state": string;
    "missing": string[];

    /** Creates a new CopilotStatus instance. */
    constructor($$source: Partial<CopilotStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("missing" in $$source)) {
            this["missing"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CopilotStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CopilotStatus {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("missing" in $$parsedSource) {
            $$parsedSource["missing"] = $$createField1_0($$parsedSource["missing"]);
        }
        return new CopilotStatus($$parsedSource as Partial<CopilotStatus>);
    }
}

export class CopilotTrailPoint {
    "x": number;
    "y": number;
    "ageMs": number;

    /** Creates a new CopilotTrailPoint instance. */
    constructor($$source: Partial<CopilotTrailPoint> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("ageMs" in $$source)) {
            this["ageMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CopilotTrailPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): CopilotTrailPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CopilotTrailPoint($$parsedSource as Partial<CopilotTrailPoint>);
    }
}

/**
 * CopilotUpdate reconciles the annotations for one capture. Artwork is sent
 * once through Frame; subsequent updates contain only position and expiry.
 */
export class CopilotUpdate {
    "sessionId": string;
    "marks": CopilotPosition[];

    /** Creates a new CopilotUpdate instance. */
    constructor($$source: Partial<CopilotUpdate> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("marks" in $$source)) {
            this["marks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CopilotUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): CopilotUpdate {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("marks" in $$parsedSource) {
            $$parsedSource["marks"] = $$createField1_0($$parsedSource["marks"]);
        }
        return new CopilotUpdate($$parsedSource as Partial<CopilotUpdate>);
    }
}

/**
 * Info is what the page needs to send frames the overlay will accept.
 */
export class Info {
    "overlayId": string;
    "width": number;
    "height": number;
    "maxWidth": number;
    "maxHeight": number;

    /**
     * MaxFrameBytes and MaxFPS let the page size and pace its own sends rather
     * than discovering the limits by being refused.
     */
    "maxFrameBytes": number;
    "maxFps": number;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("overlayId" in $$source)) {
            this["overlayId"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("maxWidth" in $$source)) {
            this["maxWidth"] = 0;
        }
        if (!("maxHeight" in $$source)) {
            this["maxHeight"] = 0;
        }
        if (!("maxFrameBytes" in $$source)) {
            this["maxFrameBytes"] = 0;
        }
        if (!("maxFps" in $$source)) {
            this["maxFps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}

/**
 * Options describe an overlay to open.
 */
export class Options {
    "position": Position;
    "size": Size;

    /**
     * ClickThrough lets the pointer reach whatever is underneath. A camera tile
     * over a game must not eat clicks.
     */
    "clickThrough": boolean;

    /**
     * Rows stacks that many 16:9 tiles vertically.
     */
    "rows": number;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("position" in $$source)) {
            this["position"] = Position.$zero;
        }
        if (!("size" in $$source)) {
            this["size"] = Size.$zero;
        }
        if (!("clickThrough" in $$source)) {
            this["clickThrough"] = false;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Options($$parsedSource as Partial<Options>);
    }
}

/**
 * Position is which corner of the display the overlay sits in.
 */
export enum Position {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TopLeft = "top-left",
    TopRight = "top-right",
    BottomLeft = "bottom-left",
    BottomRight = "bottom-right",
};

/**
 * Size is the overlay's width preset.
 */
export enum Size {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Small = "small",
    Medium = "medium",
    Large = "large",
};

/**
 * Update changes an open overlay. A nil field is left as it is.
 */
export class Update {
    "position"?: Position | null;
    "size"?: Size | null;
    "clickThrough"?: boolean | null;
    "rows"?: number | null;

    /** Creates a new Update instance. */
    constructor($$source: Partial<Update> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Update instance from a string or object.
     */
    static createFrom($$source: any = {}): Update {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Update($$parsedSource as Partial<Update>);
    }
}

// Private type creation functions
const $$createType0 = CopilotTrailPoint.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = CopilotPosition.createFrom;
const $$createType4 = $Create.Array($$createType3);
