// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Capabilities reports whether process loopback works on this machine.
 */
export class Capabilities {
    "available": boolean;
    "applicationAudio": boolean;
    "callAudioControl": boolean;
    "detail": string;
    "minimumWindowsBuild": number;

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("applicationAudio" in $$source)) {
            this["applicationAudio"] = false;
        }
        if (!("callAudioControl" in $$source)) {
            this["callAudioControl"] = false;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("minimumWindowsBuild" in $$source)) {
            this["minimumWindowsBuild"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

/**
 * Mode is what a session is capturing.
 */
export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ModeSystem is everything except this application's process tree, which is
     * what "share system audio" means during a call.
     */
    ModeSystem = "system",

    /**
     * ModeApplication is one application's process tree.
     */
    ModeApplication = "application",

    /**
     * ModeWholeSystem includes this application. Only used when the person has
     * explicitly turned call-audio exclusion off.
     */
    ModeWholeSystem = "whole-system",
};

/**
 * StartOptions is what the page asks a capture for.
 */
export class StartOptions {
    /**
     * SourceID names a capture source whose application audio to record. Empty
     * captures the system instead.
     */
    "sourceId": string;

    /**
     * ExcludeCallAudio defaults to true. Turning it off records this
     * application too, which in a call means recording the other participants.
     */
    "excludeCallAudio": boolean | null;

    /** Creates a new StartOptions instance. */
    constructor($$source: Partial<StartOptions> = {}) {
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("excludeCallAudio" in $$source)) {
            this["excludeCallAudio"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): StartOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartOptions($$parsedSource as Partial<StartOptions>);
    }
}

/**
 * Started describes a running capture.
 */
export class Started {
    "sessionId": string;
    "sampleRate": number;
    "channels": number;
    "mode": Mode;

    /** Creates a new Started instance. */
    constructor($$source: Partial<Started> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("sampleRate" in $$source)) {
            this["sampleRate"] = 0;
        }
        if (!("channels" in $$source)) {
            this["channels"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = Mode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Started instance from a string or object.
     */
    static createFrom($$source: any = {}): Started {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Started($$parsedSource as Partial<Started>);
    }
}
