// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InstallInfo is what a settings screen renders before anything is installed.
 */
export class InstallInfo {
    "schemaVersion": number;

    /**
     * Supported reports NVIDIA hardware the pinned package targets.
     */
    "supported": boolean;

    /**
     * Installed reports a complete package on disk.
     */
    "installed": boolean;

    /**
     * GPUName is the adapter this decision was made about, when there is one.
     */
    "gpuName"?: string;

    /**
     * Package names the pinned build, so a report says which one.
     */
    "package"?: string;
    "detail": string;

    /** Creates a new InstallInfo instance. */
    constructor($$source: Partial<InstallInfo> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallInfo($$parsedSource as Partial<InstallInfo>);
    }
}

/**
 * Status is what the settings screen renders.
 */
export class Status {
    "available": boolean;
    "installed": boolean;
    "detail": string;

    /**
     * FrameSamples is how many samples one call processes. Zero until a model
     * has actually loaded.
     */
    "frameSamples": number;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("frameSamples" in $$source)) {
            this["frameSamples"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
