// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Grant {
    "sessionId": string;
    "frameSamples": number;
    "sampleRate": number;
    "port": number;
    "token": string;

    /** Creates a new Grant instance. */
    constructor($$source: Partial<Grant> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("frameSamples" in $$source)) {
            this["frameSamples"] = 0;
        }
        if (!("sampleRate" in $$source)) {
            this["sampleRate"] = 0;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Grant instance from a string or object.
     */
    static createFrom($$source: any = {}): Grant {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Grant($$parsedSource as Partial<Grant>);
    }
}
