// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Adapter is one DirectML-capable graphics adapter, identified by the ordinal
 * DirectML itself will use.
 */
export class Adapter {
    "index": number;
    "name": string;
    "vendorId": number;

    /** Creates a new Adapter instance. */
    constructor($$source: Partial<Adapter> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("vendorId" in $$source)) {
            this["vendorId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Adapter instance from a string or object.
     */
    static createFrom($$source: any = {}): Adapter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Adapter($$parsedSource as Partial<Adapter>);
    }
}
