import type { CSSProperties } from 'react';
import { getDesktopRuntime, readDesktopBootReport } from './runtime';
import type { DesktopWindowControls } from './types';

/**
 * The transport for host commands.
 *
 * Tauri commands go through its IPC. Wails commands use bindings generated by
 * the pinned Wails v3 CLI. The Wails module is loaded only in that runtime, so
 * browser and Tauri builds do not execute it.
 */

/** Raised when a command has no implementation on the current runtime. */
export class DesktopUnavailableError extends Error {
  constructor(
    readonly command: string,
    readonly runtime: string,
  ) {
    super(`"${command}" is not available in the ${runtime} runtime`);
    this.name = 'DesktopUnavailableError';
  }
}

/**
 * The window operations the custom title bar needs, resolved for the current
 * runtime. Returns null in a browser, where the page draws no title bar.
 */
export interface DesktopWindowApi {
  minimize(): Promise<void>;
  toggleMaximize(): Promise<void>;
  close(): Promise<void>;
  isMaximized(): Promise<boolean>;
  /**
   * Begins a window drag. Tauri needs an IPC call for it. The Wails webview
   * starts the drag itself from the CSS drag region, so there it resolves
   * without doing anything and `dragRegionStyle` supplies the region.
   */
  startDragging(): Promise<void>;
}

/**
 * The style that marks an element as a window drag region, or an empty object.
 * Only the Wails webview reads it; Tauri drags through `startDragging`.
 */
export function dragRegionStyle(): CSSProperties {
  if (usesWailsNativeNonClientRegions()) return {};
  return wailsDraggable('drag');
}

/** The style that excludes a control inside a drag region, such as a button. */
export function noDragStyle(): CSSProperties {
  if (usesWailsNativeNonClientRegions()) return {};
  return wailsDraggable('no-drag');
}

/** Returns the DOM marker consumed by the Windows-only non-client CSS. */
export function nativeNonClientRegion(
  region: 'caption' | DesktopWindowControls['buttons'][number],
): typeof region | undefined {
  return usesWailsNativeNonClientRegions() ? region : undefined;
}

function usesWailsNativeNonClientRegions(): boolean {
  const boot = readDesktopBootReport();
  return getDesktopRuntime() === 'wails' && boot?.platform === 'windows';
}

function wailsDraggable(value: 'drag' | 'no-drag'): CSSProperties {
  if (getDesktopRuntime() !== 'wails') return {};
  // A custom property is not part of CSSProperties, which is why every custom
  // property in this codebase is asserted at the boundary.
  return { '--wails-draggable': value } as CSSProperties;
}

export function getDesktopWindowApi(): DesktopWindowApi | null {
  switch (getDesktopRuntime()) {
    case 'tauri':
      return tauriWindowApi();
    case 'wails':
      return wailsWindowApi();
    default:
      return null;
  }
}

function wailsWindowApi(): DesktopWindowApi {
  const service = () =>
    import('./wailsbindings/bettercomms/desktop-wails/windowservice.js');
  return {
    minimize: async () => (await service()).Minimise(),
    toggleMaximize: async () => (await service()).ToggleMaximise(),
    close: async () => (await service()).Close(),
    isMaximized: async () => (await service()).IsMaximised(),
    startDragging: async () => {},
  };
}

function tauriWindowApi(): DesktopWindowApi {
  // Imported lazily so a browser or Wails bundle never evaluates the Tauri
  // window module, which touches IPC globals on load.
  const current = async () =>
    (await import('@tauri-apps/api/window')).getCurrentWindow();
  return {
    minimize: async () => (await current()).minimize(),
    toggleMaximize: async () => (await current()).toggleMaximize(),
    close: async () => (await current()).close(),
    isMaximized: async () => (await current()).isMaximized(),
    startDragging: async () => (await current()).startDragging(),
  };
}
