// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Profile is the H.264 profile a native capture is encoded in.
 */
export enum Profile {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Baseline = "baseline",
    Main = "main",
    High = "high",
};
