// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as h264$0 from "../h264/models.js";

/**
 * Capabilities is what native sharing can do on this machine.
 */
export class Capabilities {
    "available": boolean;
    "detail": string;
    "encoders": Encoder[];
    "version": number;

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("encoders" in $$source)) {
            this["encoders"] = [];
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("encoders" in $$parsedSource) {
            $$parsedSource["encoders"] = $$createField2_0($$parsedSource["encoders"]);
        }
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

/**
 * Encoder is one H.264 encoder and whether this machine can actually run it.
 */
export class Encoder {
    "id": string;
    "label": string;
    "available": boolean;
    "reason": string;

    /** Creates a new Encoder instance. */
    constructor($$source: Partial<Encoder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Encoder instance from a string or object.
     */
    static createFrom($$source: any = {}): Encoder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Encoder($$parsedSource as Partial<Encoder>);
    }
}

/**
 * Source is one shareable window or display.
 */
export class Source {
    "id": string;
    "kind": string;
    "name": string;
    "width": number;
    "height": number;
    "category": string;
    "minimized": boolean;

    /** Creates a new Source instance. */
    constructor($$source: Partial<Source> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("minimized" in $$source)) {
            this["minimized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     */
    static createFrom($$source: any = {}): Source {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Source($$parsedSource as Partial<Source>);
    }
}

/**
 * StartOptions is what the page asks a capture for.
 */
export class StartOptions {
    "sourceId": string;
    "encoder": string;
    "width": number;
    "height": number;
    "fps": number;
    "bitrateMbps": number;
    "cursor": boolean;
    "displayBorder": boolean;
    "h264Profile": h264$0.Profile;

    /** Creates a new StartOptions instance. */
    constructor($$source: Partial<StartOptions> = {}) {
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("encoder" in $$source)) {
            this["encoder"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("fps" in $$source)) {
            this["fps"] = 0;
        }
        if (!("bitrateMbps" in $$source)) {
            this["bitrateMbps"] = 0;
        }
        if (!("cursor" in $$source)) {
            this["cursor"] = false;
        }
        if (!("displayBorder" in $$source)) {
            this["displayBorder"] = false;
        }
        if (!("h264Profile" in $$source)) {
            this["h264Profile"] = h264$0.Profile.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): StartOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartOptions($$parsedSource as Partial<StartOptions>);
    }
}

/**
 * Started describes a capture that is now running.
 */
export class Started {
    "sessionId": string;
    "width": number;
    "height": number;
    "fps": number;
    "encoder": string;
    "h264Profile": h264$0.Profile;
    "bitrateMbps": number;

    /** Creates a new Started instance. */
    constructor($$source: Partial<Started> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("fps" in $$source)) {
            this["fps"] = 0;
        }
        if (!("encoder" in $$source)) {
            this["encoder"] = "";
        }
        if (!("h264Profile" in $$source)) {
            this["h264Profile"] = h264$0.Profile.$zero;
        }
        if (!("bitrateMbps" in $$source)) {
            this["bitrateMbps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Started instance from a string or object.
     */
    static createFrom($$source: any = {}): Started {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Started($$parsedSource as Partial<Started>);
    }
}

// Private type creation functions
const $$createType0 = Encoder.createFrom;
const $$createType1 = $Create.Array($$createType0);
