// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Capabilities is the set of conversion targets.
 */
export class Capabilities {
    "formats": Capability[];

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("formats" in $$source)) {
            this["formats"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formats" in $$parsedSource) {
            $$parsedSource["formats"] = $$createField0_0($$parsedSource["formats"]);
        }
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

/**
 * Capability is one conversion target and whether this machine can produce it.
 */
export class Capability {
    "id": string;
    "extension": string;
    "label": string;
    "available": boolean;

    /** Creates a new Capability instance. */
    constructor($$source: Partial<Capability> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("extension" in $$source)) {
            this["extension"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capability instance from a string or object.
     */
    static createFrom($$source: any = {}): Capability {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capability($$parsedSource as Partial<Capability>);
    }
}

/**
 * Grant is the opaque handle the page uses to stream into a chosen file.
 */
export class Grant {
    "exportId": string;

    /** Creates a new Grant instance. */
    constructor($$source: Partial<Grant> = {}) {
        if (!("exportId" in $$source)) {
            this["exportId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Grant instance from a string or object.
     */
    static createFrom($$source: any = {}): Grant {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Grant($$parsedSource as Partial<Grant>);
    }
}

/**
 * Result is where a completed export landed.
 */
export class Result {
    "fileName": string;

    /**
     * Path is shown to the person so they can find the file. It is only ever
     * a location they chose themselves in the save dialog.
     */
    "path": string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}

// Private type creation functions
const $$createType0 = Capability.createFrom;
const $$createType1 = $Create.Array($$createType0);
