// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MediaPermissionKind is a capability the page can ask for.
 */
export enum MediaPermissionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MicrophonePermission = "microphone",
    CameraPermission = "camera",
};

/**
 * MediaPermissionPolicy is what this host configured, and what it cannot do.
 */
export class MediaPermissionPolicy {
    "kind": MediaPermissionKind;

    /**
     * Policy is what the window was configured with: "allow" means capture
     * proceeds without a webview prompt.
     */
    "policy": string;

    /**
     * Managed reports whether this host can change the policy at runtime. It is
     * false here, and the page should not offer a control that would do
     * nothing.
     */
    "managed": boolean;

    /**
     * Detail is what to tell the person when capture fails anyway.
     */
    "detail": string;

    /** Creates a new MediaPermissionPolicy instance. */
    constructor($$source: Partial<MediaPermissionPolicy> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = MediaPermissionKind.$zero;
        }
        if (!("policy" in $$source)) {
            this["policy"] = "";
        }
        if (!("managed" in $$source)) {
            this["managed"] = false;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaPermissionPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaPermissionPolicy {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaPermissionPolicy($$parsedSource as Partial<MediaPermissionPolicy>);
    }
}

/**
 * SignInState is the stage the browser hand-off has reached.
 */
export enum SignInState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * SignInIdle means no sign-in is in progress.
     */
    SignInIdle = "idle",

    /**
     * SignInWaiting means the browser has it and this process is polling.
     */
    SignInWaiting = "waiting",

    /**
     * SignInComplete means the session is in this process's jar.
     */
    SignInComplete = "complete",

    /**
     * SignInFailed means the attempt ended without a session, for the stated
     * reason.
     */
    SignInFailed = "failed",
};

/**
 * SignInStatus is what the window shows while it waits.
 */
export class SignInStatus {
    "state": SignInState;

    /**
     * Code is the confirmation code the browser page will display. The person
     * compares the two before approving, which is what stops a link to someone
     * else's sign-in from signing them into it.
     */
    "code"?: string;

    /**
     * ConfirmURL is the page the browser was sent to, so the window can offer
     * it again if the browser did not open or was closed.
     */
    "confirmUrl"?: string;

    /**
     * Detail explains the state in the words the window should show.
     */
    "detail": string;

    /**
     * ExpiresAt is when this attempt stops being claimable, in Unix
     * milliseconds. Zero when nothing is pending.
     */
    "expiresAt"?: number;

    /** Creates a new SignInStatus instance. */
    constructor($$source: Partial<SignInStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = SignInState.$zero;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SignInStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SignInStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SignInStatus($$parsedSource as Partial<SignInStatus>);
    }
}
