// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * IceCandidate is a trickled candidate from the viewer.
 */
export class IceCandidate {
    "candidate": string;
    "sdpMid": string | null;
    "sdpMLineIndex": number | null;

    /** Creates a new IceCandidate instance. */
    constructor($$source: Partial<IceCandidate> = {}) {
        if (!("candidate" in $$source)) {
            this["candidate"] = "";
        }
        if (!("sdpMid" in $$source)) {
            this["sdpMid"] = null;
        }
        if (!("sdpMLineIndex" in $$source)) {
            this["sdpMLineIndex"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IceCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): IceCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IceCandidate($$parsedSource as Partial<IceCandidate>);
    }
}

/**
 * IceServer is an ICE server as the page supplies it.
 */
export class IceServer {
    "urls": string[];
    "username": string;
    "credential": string;

    /** Creates a new IceServer instance. */
    constructor($$source: Partial<IceServer> = {}) {
        if (!("urls" in $$source)) {
            this["urls"] = [];
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("credential" in $$source)) {
            this["credential"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IceServer instance from a string or object.
     */
    static createFrom($$source: any = {}): IceServer {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField0_0($$parsedSource["urls"]);
        }
        return new IceServer($$parsedSource as Partial<IceServer>);
    }
}

/**
 * Offer is what the page relays to the viewer.
 */
export class Offer {
    "peerId": string;
    "sdp": string;

    /** Creates a new Offer instance. */
    constructor($$source: Partial<Offer> = {}) {
        if (!("peerId" in $$source)) {
            this["peerId"] = "";
        }
        if (!("sdp" in $$source)) {
            this["sdp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Offer instance from a string or object.
     */
    static createFrom($$source: any = {}): Offer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Offer($$parsedSource as Partial<Offer>);
    }
}

/**
 * Stats is what the capture has produced so far.
 */
export class Stats {
    "accessUnits": number;
    "keyframes": number;
    "encodedBytes": number;
    "droppedFrames": number;
    "peers": number;

    /**
     * SPSProfileIDC and friends describe the stream the encoder actually
     * produced, which is what proves it honoured the profile it was given.
     */
    "spsProfileIdc"?: string;
    "spsConstraintFlags"?: string;
    "spsLevelIdc"?: string;

    /** Creates a new Stats instance. */
    constructor($$source: Partial<Stats> = {}) {
        if (!("accessUnits" in $$source)) {
            this["accessUnits"] = 0;
        }
        if (!("keyframes" in $$source)) {
            this["keyframes"] = 0;
        }
        if (!("encodedBytes" in $$source)) {
            this["encodedBytes"] = 0;
        }
        if (!("droppedFrames" in $$source)) {
            this["droppedFrames"] = 0;
        }
        if (!("peers" in $$source)) {
            this["peers"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     */
    static createFrom($$source: any = {}): Stats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats($$parsedSource as Partial<Stats>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
