DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='messages' AND column_name='sequence') THEN
    ALTER TABLE messages ADD COLUMN sequence bigint GENERATED BY DEFAULT AS IDENTITY;
    UPDATE messages SET sequence=ordered.n FROM (SELECT id,row_number() OVER (ORDER BY created_at,id) n FROM messages) ordered WHERE messages.id=ordered.id;
    PERFORM setval(pg_get_serial_sequence('messages','sequence'),GREATEST(COALESCE(max(sequence),0),1),COALESCE(max(sequence),0)>0) FROM messages;
  END IF;
END $$;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS edited_at timestamptz;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS reply_to_id uuid REFERENCES messages(id);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS version bigint NOT NULL DEFAULT 1;
ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_body_check;
ALTER TABLE messages ADD CONSTRAINT messages_body_check CHECK
  ((deleted_at IS NULL AND char_length(body) BETWEEN 1 AND 4000) OR (deleted_at IS NOT NULL AND body = ''));
CREATE UNIQUE INDEX IF NOT EXISTS messages_sequence_unique ON messages(sequence);
CREATE INDEX IF NOT EXISTS messages_room_sequence ON messages(room_id,sequence DESC);
CREATE INDEX IF NOT EXISTS messages_search ON messages USING gin(to_tsvector('simple',body)) WHERE deleted_at IS NULL;
CREATE TABLE IF NOT EXISTS message_mentions (
  message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY(message_id,user_id)
);
CREATE TABLE IF NOT EXISTS message_reactions (
  message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  emoji text NOT NULL,
  PRIMARY KEY(message_id,user_id,emoji)
);
CREATE TABLE IF NOT EXISTS room_reads (
  room_id uuid NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  sequence bigint NOT NULL DEFAULT 0,
  PRIMARY KEY(room_id,user_id)
);
