// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService is the window's view of the browser sign-in hand-off.
 * 
 * It is three methods on purpose. The window starts a sign-in, shows the code
 * the browser will display, and polls until the host has a session; it never
 * sees the verifier, the pairing, or the session cookie, all of which stay in
 * this process.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "./internal/desktop/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../encoding/json/models.js";

/**
 * BrowserSignInBegin opens the system browser on the confirmation page and
 * starts waiting. The returned status carries the code to display.
 */
export function BrowserSignInBegin(): $CancellablePromise<desktop$0.SignInStatus> {
    return $Call.ByID(919450828).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BrowserSignInCancel stops waiting for a sign-in the person walked away from.
 */
export function BrowserSignInCancel(): $CancellablePromise<void> {
    return $Call.ByID(668189725);
}

/**
 * BrowserSignInStatus is how far the sign-in has got. The window polls it while
 * waiting, and reloads its session when it reports complete.
 */
export function BrowserSignInStatus(): $CancellablePromise<desktop$0.SignInStatus> {
    return $Call.ByID(757607053).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IOSCallAudioStart(hostToken: string): $CancellablePromise<void> {
    return $Call.ByID(1172425750, hostToken);
}

export function IOSCallAudioStop(hostToken: string): $CancellablePromise<void> {
    return $Call.ByID(1198987198, hostToken);
}

export function IOSMetaConnect(hostToken: string): $CancellablePromise<void> {
    return $Call.ByID(412519885, hostToken);
}

/**
 * The page must present its native host capability before changing any sender.
 */
export function IOSMetaSender(token: string, command: string, raw: json$0.RawMessage): $CancellablePromise<any> {
    return $Call.ByID(818610616, token, command, raw);
}

export function IOSMetaStart(hostToken: string): $CancellablePromise<void> {
    return $Call.ByID(1795186331, hostToken);
}

export function IOSMetaStop(hostToken: string): $CancellablePromise<void> {
    return $Call.ByID(2309734089, hostToken);
}

export function IOSScreenSender(hostToken: string, command: string, args: json$0.RawMessage): $CancellablePromise<any> {
    return $Call.ByID(6783441, hostToken, command, args);
}

export function IOSScreenStart(hostToken: string): $CancellablePromise<void> {
    return $Call.ByID(4164795156, hostToken);
}

export function IOSScreenStop(hostToken: string): $CancellablePromise<void> {
    return $Call.ByID(3307136720, hostToken);
}

// Private type creation functions
const $$createType0 = desktop$0.SignInStatus.createFrom;
