// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService is the window's view of the browser sign-in hand-off.
 * 
 * It is three methods on purpose. The window starts a sign-in, shows the code
 * the browser will display, and polls until the host has a session; it never
 * sees the verifier, the pairing, or the session cookie, all of which stay in
 * this process.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "./internal/desktop/models.js";

/**
 * BrowserSignInBegin opens the system browser on the confirmation page and
 * starts waiting. The returned status carries the code to display.
 */
export function BrowserSignInBegin(): $CancellablePromise<desktop$0.SignInStatus> {
    return $Call.ByID(919450828).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BrowserSignInCancel stops waiting for a sign-in the person walked away from.
 */
export function BrowserSignInCancel(): $CancellablePromise<void> {
    return $Call.ByID(668189725);
}

/**
 * BrowserSignInStatus is how far the sign-in has got. The window polls it while
 * waiting, and reloads its session when it reports complete.
 */
export function BrowserSignInStatus(): $CancellablePromise<desktop$0.SignInStatus> {
    return $Call.ByID(757607053).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = desktop$0.SignInStatus.createFrom;
