// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Activity(pageToken: string, id: string, active: boolean): $CancellablePromise<void> {
    return $Call.ByID(375368109, pageToken, id, active);
}

export function Cancel(pageToken: string): $CancellablePromise<void> {
    return $Call.ByID(2722300682, pageToken);
}

export function Check(pageToken: string): $CancellablePromise<$models.DesktopUpdateStatus> {
    return $Call.ByID(46483848, pageToken).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Download(pageToken: string): $CancellablePromise<$models.DesktopUpdateStatus> {
    return $Call.ByID(4202236320, pageToken).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Restart(pageToken: string): $CancellablePromise<void> {
    return $Call.ByID(1864549083, pageToken);
}

export function SetAutomatic(pageToken: string, enabled: boolean): $CancellablePromise<$models.DesktopUpdateStatus> {
    return $Call.ByID(3456536559, pageToken, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Status(pageToken: string): $CancellablePromise<$models.DesktopUpdateStatus> {
    return $Call.ByID(1146875826, pageToken).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DesktopUpdateStatus.createFrom;
