// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as startup$0 from "./internal/desktop/startup/models.js";

export function StartupSetEnabled(pageToken: string, enabled: boolean): $CancellablePromise<startup$0.Status> {
    return $Call.ByID(1473097289, pageToken, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StartupStatus(pageToken: string): $CancellablePromise<startup$0.Status> {
    return $Call.ByID(623095930, pageToken).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = startup$0.Status.createFrom;
