// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as h264$0 from "./internal/native/h264/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativertc$0 from "./internal/native/nativertc/models.js";

/**
 * NativeScreenReport is a capture's live state.
 */
export class NativeScreenReport {
    "sessionId": string;
    "width": number;
    "height": number;
    "fps": number;
    "encoder": string;
    "h264Profile": h264$0.Profile;
    "bitrateMbps": number;
    "stats": nativertc$0.Stats;

    /**
     * EncoderOutput is the encoder's own diagnostics, which is what explains a
     * capture that started and then failed.
     */
    "encoderOutput"?: string;

    /** Creates a new NativeScreenReport instance. */
    constructor($$source: Partial<NativeScreenReport> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("fps" in $$source)) {
            this["fps"] = 0;
        }
        if (!("encoder" in $$source)) {
            this["encoder"] = "";
        }
        if (!("h264Profile" in $$source)) {
            this["h264Profile"] = h264$0.Profile.$zero;
        }
        if (!("bitrateMbps" in $$source)) {
            this["bitrateMbps"] = 0;
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new nativertc$0.Stats());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NativeScreenReport instance from a string or object.
     */
    static createFrom($$source: any = {}): NativeScreenReport {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField7_0($$parsedSource["stats"]);
        }
        return new NativeScreenReport($$parsedSource as Partial<NativeScreenReport>);
    }
}

// Private type creation functions
const $$createType0 = nativertc$0.Stats.createFrom;
