// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NativeMediaService is the binding surface for the ported native media stack.
 * 
 * Every method here is a thin shim. The behaviour lives in internal/native,
 * which imports no Wails package, so all of it stays testable with `go test`
 * and none of it depends on a window existing.
 * 
 * The page never supplies a window handle, a process id, or a filesystem path.
 * It names a capture source by an opaque id this host issued, and reads a
 * recording by an opaque asset id, so a compromised page cannot aim capture or
 * file reads at anything it was not offered.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "./internal/desktop/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audiostream$0 from "./internal/native/audiostream/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as deepfilter$0 from "./internal/native/deepfilter/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dspsetup$0 from "./internal/native/dspsetup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ffmpegsetup$0 from "./internal/native/ffmpegsetup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gpudevices$0 from "./internal/native/gpudevices/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativerecording$0 from "./internal/native/nativerecording/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativertc$0 from "./internal/native/nativertc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativescreen$0 from "./internal/native/nativescreen/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nvidiaaudio$0 from "./internal/native/nvidiaaudio/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as overlay$0 from "./internal/native/overlay/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pushtotalk$0 from "./internal/native/pushtotalk/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recordingexport$0 from "./internal/native/recordingexport/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as systemaudio$0 from "./internal/native/systemaudio/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AudioStreamStart creates one isolated DSP session for the existing binary
 * Worker/AudioWorklet path. No PCM frames cross Wails' JSON binding channel.
 */
export function AudioStreamStart(hostToken: string, engine: string, intensity: number, vad: boolean, attenuationDB: number): $CancellablePromise<audiostream$0.Grant> {
    return $Call.ByID(308276026, hostToken, engine, intensity, vad, attenuationDB).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AudioStreamStop(hostToken: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4126532122, hostToken, sessionID);
}

/**
 * CameraOverlayClose hides the overlay.
 */
export function CameraOverlayClose(hostToken: string, overlayID: string): $CancellablePromise<void> {
    return $Call.ByID(3524078643, hostToken, overlayID);
}

/**
 * CameraOverlayFrame paints one RGBA frame.
 * 
 * The frame arrives as bytes rather than a data URL: a 320x180 tile at 24 fps
 * is about 5 MB a second, and base64 would add a third to that for nothing.
 */
export function CameraOverlayFrame(hostToken: string, overlayID: string, width: number, height: number, rgba: string): $CancellablePromise<void> {
    return $Call.ByID(261208182, hostToken, overlayID, width, height, rgba);
}

/**
 * CameraOverlayOpen shows the always-on-top camera tile, replacing any that was
 * already open.
 */
export function CameraOverlayOpen(hostToken: string, options: overlay$0.Options): $CancellablePromise<overlay$0.Info> {
    return $Call.ByID(980661433, hostToken, options).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CameraOverlayUpdate moves or resizes an open overlay.
 */
export function CameraOverlayUpdate(hostToken: string, overlayID: string, change: overlay$0.Update): $CancellablePromise<overlay$0.Info> {
    return $Call.ByID(2830156644, hostToken, overlayID, change).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CopilotOverlayClear takes every signal off the desktop. The page calls it
 * when the marks expire, when sharing stops, and once at startup to find out
 * whether this host supports the overlay at all.
 */
export function CopilotOverlayClear(hostToken: string): $CancellablePromise<void> {
    return $Call.ByID(2511202781, hostToken);
}

/**
 * CopilotOverlayFrame draws one visual-copilot signal over the shared source.
 * 
 * The signal is placed against a capture session this host started, not against
 * a window the page names, so a page cannot put a window at an arbitrary place
 * on the desktop by claiming to be pointing at something.
 */
export function CopilotOverlayFrame(hostToken: string, frame: overlay$0.CopilotFrame, rgba: string): $CancellablePromise<void> {
    return $Call.ByID(1165291229, hostToken, frame, rgba);
}

export function DeepfilterInstall(hostToken: string): $CancellablePromise<dspsetup$0.Result> {
    return $Call.ByID(833623355, hostToken).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeepfilterInstallInfo(): $CancellablePromise<dspsetup$0.Info> {
    return $Call.ByID(2543425375).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DeepfilterStatus reports whether the package is installed and which GPU the
 * graph would run on.
 */
export function DeepfilterStatus(hostToken: string): $CancellablePromise<deepfilter$0.Status> {
    return $Call.ByID(2720805130, hostToken).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * FfmpegInstall downloads and verifies the pinned runtime.
 */
export function FfmpegInstall(hostToken: string): $CancellablePromise<ffmpegsetup$0.InstallResult> {
    return $Call.ByID(920664444, hostToken).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * FfmpegInstallInfo reports whether the private FFmpeg runtime is present.
 */
export function FfmpegInstallInfo(): $CancellablePromise<ffmpegsetup$0.InstallInfo> {
    return $Call.ByID(3471164480).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GpuAdapters lists the DirectML-capable adapters on this machine.
 */
export function GpuAdapters(): $CancellablePromise<gpudevices$0.Adapter[]> {
    return $Call.ByID(3888399434).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * MediaPermission reports the standing policy this host configured for a
 * capability, and whether it can be changed from here.
 * 
 * The page asks so it can render the truth rather than a control that would do
 * nothing: this host allows capture outright and cannot revoke it, which is a
 * different shape from the Tauri host's per-origin grant.
 */
export function MediaPermission(kind: string): $CancellablePromise<desktop$0.MediaPermissionPolicy> {
    return $Call.ByID(3965183451, kind).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * MediaPermissionOpenSettings opens the Windows privacy page for a capability.
 * 
 * This is where a refusal actually lives on Windows: the webview is configured
 * to allow capture, so a device that will not open is being held by the
 * operating system, not by this application.
 */
export function MediaPermissionOpenSettings(hostToken: string, kind: string): $CancellablePromise<void> {
    return $Call.ByID(3048323386, hostToken, kind);
}

/**
 * NativeScreenCapabilities probes the encoders this machine can actually run.
 */
export function NativeScreenCapabilities(): $CancellablePromise<nativescreen$0.Capabilities> {
    return $Call.ByID(1992205581).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * NativeScreenDiagnostics reports what a running capture is doing.
 */
export function NativeScreenDiagnostics(hostToken: string, sessionID: string): $CancellablePromise<$models.NativeScreenReport> {
    return $Call.ByID(2708561293, hostToken, sessionID).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * NativeScreenPeerAnswer accepts a viewer's answer.
 */
export function NativeScreenPeerAnswer(hostToken: string, sessionID: string, peerID: string, sdp: string): $CancellablePromise<void> {
    return $Call.ByID(3873781057, hostToken, sessionID, peerID, sdp);
}

/**
 * NativeScreenPeerCandidate trickles one ICE candidate in.
 */
export function NativeScreenPeerCandidate(hostToken: string, sessionID: string, peerID: string, candidate: nativertc$0.IceCandidate): $CancellablePromise<void> {
    return $Call.ByID(569652104, hostToken, sessionID, peerID, candidate);
}

/**
 * NativeScreenPeerOffer offers the capture to one viewer.
 */
export function NativeScreenPeerOffer(hostToken: string, sessionID: string, peerID: string, iceServers: nativertc$0.IceServer[], directOnly: boolean): $CancellablePromise<nativertc$0.Offer> {
    return $Call.ByID(1196821571, hostToken, sessionID, peerID, iceServers, directOnly).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * NativeScreenPeerRemove detaches one viewer.
 */
export function NativeScreenPeerRemove(hostToken: string, sessionID: string, peerID: string): $CancellablePromise<void> {
    return $Call.ByID(3424094475, hostToken, sessionID, peerID);
}

/**
 * NativeScreenRecordingRead returns one chunk of a finished recording. The page
 * never learns where the file lives.
 */
export function NativeScreenRecordingRead(hostToken: string, assetID: string, offset: number, length: number): $CancellablePromise<string> {
    return $Call.ByID(903583178, hostToken, assetID, offset, length).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * NativeScreenRecordingRelease deletes a finished recording.
 */
export function NativeScreenRecordingRelease(hostToken: string, assetID: string): $CancellablePromise<void> {
    return $Call.ByID(1620232963, hostToken, assetID);
}

/**
 * NativeScreenRecordingStart records the live capture without re-encoding it.
 */
export function NativeScreenRecordingStart(hostToken: string, sessionID: string): $CancellablePromise<nativerecording$0.Started> {
    return $Call.ByID(3237331130, hostToken, sessionID).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * NativeScreenRecordingStop finalises the MP4 and returns its handle.
 */
export function NativeScreenRecordingStop(hostToken: string, recordingID: string): $CancellablePromise<nativerecording$0.Asset> {
    return $Call.ByID(291776154, hostToken, recordingID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * NativeScreenSources lists what can be shared.
 */
export function NativeScreenSources(hostToken: string): $CancellablePromise<nativescreen$0.Source[]> {
    return $Call.ByID(2824837235, hostToken).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * NativeScreenStart begins a capture.
 */
export function NativeScreenStart(hostToken: string, options: nativescreen$0.StartOptions): $CancellablePromise<nativescreen$0.Started> {
    return $Call.ByID(281183853, hostToken, options).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * NativeScreenStop ends a capture.
 */
export function NativeScreenStop(hostToken: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1122224799, hostToken, sessionID);
}

export function NativeScreenThumbnail(hostToken: string, sourceID: string): $CancellablePromise<string> {
    return $Call.ByID(2449242269, hostToken, sourceID).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * NativeSystemAudioCapabilities reports whether process loopback works here.
 */
export function NativeSystemAudioCapabilities(): $CancellablePromise<systemaudio$0.Capabilities> {
    return $Call.ByID(2687899754).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * NativeSystemAudioRead returns the next chunk of captured audio as 48 kHz
 * stereo 32-bit float frames.
 */
export function NativeSystemAudioRead(hostToken: string, sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(3878220160, hostToken, sessionID).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * NativeSystemAudioStart begins capturing what other applications are playing.
 * 
 * The source id is resolved by the capture manager, so the page can only ever
 * name an application it was already offered in the picker.
 */
export function NativeSystemAudioStart(hostToken: string, options: systemaudio$0.StartOptions): $CancellablePromise<systemaudio$0.Started> {
    return $Call.ByID(961568448, hostToken, options).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * NativeSystemAudioStop ends a capture.
 */
export function NativeSystemAudioStop(hostToken: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2277855364, hostToken, sessionID);
}

export function NvidiaInstall(hostToken: string): $CancellablePromise<dspsetup$0.Result> {
    return $Call.ByID(4119064850, hostToken).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * NvidiaInstallInfo reports whether this machine has hardware the pinned
 * package runs on, and whether the package is already here.
 * 
 * It answers before anything is loaded, so a settings screen can offer an
 * install, say which card would be needed, or point at DeepFilterNet — rather
 * than offering a several-hundred-megabyte download that would not work.
 */
export function NvidiaInstallInfo(): $CancellablePromise<dspsetup$0.Info> {
    return $Call.ByID(631349290).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * NvidiaStatus reports whether the SDK is installed and whether this machine's
 * GPU will actually run it.
 */
export function NvidiaStatus(hostToken: string): $CancellablePromise<nvidiaaudio$0.Status> {
    return $Call.ByID(260844949, hostToken).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * PushToTalkCapabilities reports whether background push-to-talk works here.
 */
export function PushToTalkCapabilities(): $CancellablePromise<pushtotalk$0.Capabilities> {
    return $Call.ByID(3053704157).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * PushToTalkHeartbeat renews the session lease.
 */
export function PushToTalkHeartbeat(hostToken: string, sessionID: string): $CancellablePromise<pushtotalk$0.Snapshot> {
    return $Call.ByID(2695015501, hostToken, sessionID).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * PushToTalkStart watches one key or mouse button while the app is in the
 * background.
 */
export function PushToTalkStart(hostToken: string, binding: pushtotalk$0.Binding): $CancellablePromise<pushtotalk$0.Snapshot> {
    return $Call.ByID(1948783421, hostToken, binding).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * PushToTalkStop ends the session and removes the hook.
 */
export function PushToTalkStop(hostToken: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1233603759, hostToken, sessionID);
}

/**
 * RecordingConversionBegin is RecordingExportBegin for a converted copy.
 */
export function RecordingConversionBegin(hostToken: string, fileName: string, sizeBytes: number, format: string): $CancellablePromise<recordingexport$0.Grant | null> {
    return $Call.ByID(2857434476, hostToken, fileName, sizeBytes, format).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * RecordingConversionCapabilities reports which conversion targets this
 * machine can produce.
 */
export function RecordingConversionCapabilities(): $CancellablePromise<recordingexport$0.Capabilities> {
    return $Call.ByID(3760024825).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * RecordingExportAbort discards an export the page gave up on.
 */
export function RecordingExportAbort(hostToken: string, exportID: string): $CancellablePromise<void> {
    return $Call.ByID(3560001453, hostToken, exportID);
}

/**
 * RecordingExportAppend writes one chunk at the offset the last one ended.
 */
export function RecordingExportAppend(hostToken: string, exportID: string, offset: number, chunk: string): $CancellablePromise<void> {
    return $Call.ByID(1068860213, hostToken, exportID, offset, chunk);
}

/**
 * RecordingExportBegin asks where to save a recording and grants the page a
 * handle to stream it there. An empty grant means the person cancelled.
 */
export function RecordingExportBegin(hostToken: string, fileName: string, sizeBytes: number): $CancellablePromise<recordingexport$0.Grant | null> {
    return $Call.ByID(2606681434, hostToken, fileName, sizeBytes).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * RecordingExportFinish commits the file, converting it first when asked.
 */
export function RecordingExportFinish(hostToken: string, exportID: string): $CancellablePromise<recordingexport$0.Result> {
    return $Call.ByID(3602689054, hostToken, exportID).then(($result: any) => {
        return $$createType26($result);
    });
}

// Private type creation functions
const $$createType0 = audiostream$0.Grant.createFrom;
const $$createType1 = overlay$0.Info.createFrom;
const $$createType2 = dspsetup$0.Result.createFrom;
const $$createType3 = dspsetup$0.Info.createFrom;
const $$createType4 = deepfilter$0.Status.createFrom;
const $$createType5 = ffmpegsetup$0.InstallResult.createFrom;
const $$createType6 = ffmpegsetup$0.InstallInfo.createFrom;
const $$createType7 = gpudevices$0.Adapter.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = desktop$0.MediaPermissionPolicy.createFrom;
const $$createType10 = nativescreen$0.Capabilities.createFrom;
const $$createType11 = $models.NativeScreenReport.createFrom;
const $$createType12 = nativertc$0.Offer.createFrom;
const $$createType13 = nativerecording$0.Started.createFrom;
const $$createType14 = nativerecording$0.Asset.createFrom;
const $$createType15 = nativescreen$0.Source.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = nativescreen$0.Started.createFrom;
const $$createType18 = systemaudio$0.Capabilities.createFrom;
const $$createType19 = systemaudio$0.Started.createFrom;
const $$createType20 = nvidiaaudio$0.Status.createFrom;
const $$createType21 = pushtotalk$0.Capabilities.createFrom;
const $$createType22 = pushtotalk$0.Snapshot.createFrom;
const $$createType23 = recordingexport$0.Grant.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = recordingexport$0.Capabilities.createFrom;
const $$createType26 = recordingexport$0.Result.createFrom;
