// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayService owns a device-wide opt-in preference. Hiding preserves the
 * webview and its notification socket; Quit closes the process explicitly.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Enabled(pageToken: string): $CancellablePromise<boolean> {
    return $Call.ByID(120619466, pageToken);
}

export function SetEnabled(pageToken: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2743806428, pageToken, enabled);
}
