// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService is the intentionally small Wails binding surface used by the
 * shared title bar. It contains no media, filesystem, process, or auth APIs.
 * Wails generates the matching TypeScript client into apps/web/src/desktop.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(3687130319);
}

export function IsFullscreen(): $CancellablePromise<boolean> {
    return $Call.ByID(1414357132);
}

export function IsMaximised(): $CancellablePromise<boolean> {
    return $Call.ByID(914905918);
}

export function Minimise(): $CancellablePromise<void> {
    return $Call.ByID(147975292);
}

export function ToggleMaximise(): $CancellablePromise<void> {
    return $Call.ByID(3549911582);
}
