// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Info {
    "schemaVersion": number;
    "supported": boolean;
    "installed": boolean;
    "gpuName"?: string;
    "selectedPackage"?: string;
    "downloadBytes": number;
    "detail": string;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("downloadBytes" in $$source)) {
            this["downloadBytes"] = 0;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}

export class Result {
    "installed": boolean;
    "destination": string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}
